---
# tasks file for common-packages
  - name: "{{ 'Remove' if (common_packages_behavior == 'remove') else 'Install' }} common packages"
    ansible.builtin.package:
      name: "{{ item }}"
      state: "{{ 'absent' if (common_packages_behavior == 'remove') else 'present' }}"
    with_items: "{{ common_packages_list }}"
    tags: 
      - common
      - package 
...