---
  - name: Deploy database Mysql server
    hosts: [db_servers]
    become: true
    vars:
      common_packages_behavior: remove
      python_packages_behavior: remove
    roles:
      - mysql-remove
      - common-packages
      - python-packages

  - name: Deploy a web server
    hosts: [app_servers]
    become: true
    vars:
      common_packages_behavior: remove
      python_packages_behavior: remove
      frontend_packages_behavior: remove
    roles:
      - common-packages
      - python-packages
      - frontend-packages
...