---
   
  - name: Deploy database Mysql server
    hosts: [db_servers]
    become: true
    roles:
      - common-packages
      - python-packages
      - mysql-install
      - mail

  - name: Deploy a web server
    hosts: [frontend_servers]
    become: true
    roles:
      - common-packages
      - python-packages
      - frontend-packages
      - mail

  - name: Deploy a load balancer
    hosts: [lb_servers]
    become: true
    roles: 
      - common-packages
      - { role: geerlingguy.haproxy }
      - mail
...