---
# tasks file for frontend-packages
  - include_tasks: stop.yml  
    when: frontend_packages_behavior == 'remove'

  - include_tasks: packages.yml  
  - include_tasks: configure.yml  
  - include_tasks: service.yml

  - include_tasks: start.yml  
    when: frontend_packages_behavior == 'install'
...