---
# tasks file for mysql-remove

  - name: Stop mysql service
    ansible.builtin.service:
      name: mysql
      state: stopped
      enabled: false
  
  - name: Remove Mysql packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent
    with_items: 
      - default-mysql-server 
      - default-mysql-client 

  - name: Remove MySQL .my.cnf
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.my.cnf
      - /var/lib/mysql
      - /usr/lib/mysql
      - /var/run/mysqld
      - /usr/bin/mysql_install_db
      - /etc/systemd/system/mariadb.service.d
...