---
# defaults file for python-packages
python_packages_behavior: install
python_packages_list:
  - python3 
  - python-setuptools 
  - python3-dev 
  - build-essential 
  - python3-pip 
  - python3-mysqldb