---
# tasks file for python-packages
  - name: "{{ 'Remove' if (common_packages_behavior == 'remove') else 'Install' }} Python packages"
    ansible.builtin.package:
      name: "{{ item }}"
      state: "{{ 'absent' if (common_packages_behavior == 'remove') else 'present' }}"
    with_items: "{{ python_packages_list }}"
    tags: 
      - python
      - package
...